### ISSUE TITLE
Fresh clone, npm install, electron error

### ISSUE THREAD

**Issue by sebbean** [stellar-comet/comet#2]
### Description

fresh clone and npm install (happens with yarn and pnpm as well)

related to: 
`node_modules/.pnpm/electron@31.3.1/node_modules/electron: Running postinstall script...`

npm
```
npm ERR! code 1
npm ERR! path /Users/seb/dev/Audio-Stream/comet/node_modules/electron
npm ERR! command failed
npm ERR! command sh -c node install.js
npm ERR! ReadError: The server aborted pending request
npm ERR!     at IncomingMessage.<anonymous> (/Users/seb/dev/Audio-Stream/comet/node_modules/got/dist/source/core/index.js:809:31)
npm ERR!     at Object.onceWrapper (node:events:631:28)
npm ERR!     at IncomingMessage.emit (node:events:529:35)
npm ERR!     at origin.emit (/Users/seb/dev/Audio-Stream/comet/node_modules/@szmarczak/http-timer/dist/source/index.js:43:20)
npm ERR!     at IncomingMessage._destroy (node:_http_incoming:224:10)
npm ERR!     at _destroy (node:internal/streams/destroy:109:10)
npm ERR!     at IncomingMessage.destroy (node:internal/streams/destroy:71:5)
npm ERR!     at TLSSocket.socketCloseListener (node:_http_client:461:11)
npm ERR!     at TLSSocket.emit (node:events:529:35)
npm ERR!     at node:net:350:12
```
yarn
```
error /Users/seb/dev/Audio-Stream/comet/node_modules/electron: Command failed.
Exit code: 1
Command: node install.js
Arguments: 
Directory: /Users/seb/dev/Audio-Stream/comet/node_modules/electron
Output:
ReadError: The server aborted pending request
    at IncomingMessage.<anonymous> (/Users/seb/dev/Audio-Stream/comet/node_modules/got/dist/source/core/index.js:809:31)
    at Object.onceWrapper (node:events:631:28)
    at IncomingMessage.emit (node:events:529:35)
    at origin.emit (/Users/seb/dev/Audio-Stream/comet/node_modules/@szmarczak/http-timer/dist/source/index.js:43:20)
    at IncomingMessage._destroy (node:_http_incoming:224:10)
    at _destroy (node:internal/streams/destroy:109:10)
    at IncomingMessage.destroy (node:internal/streams/destroy:71:5)
```

### Steps To Reproduce
1. git clone
2. npm i

**Comment by sebbean** [comment]
does seem to work eventually -
could be an inconsistent api call failing for me but not always

**Comment by Thavarshan** [comment]
hey @sebbean, thanks for the feedback! yeah the postinstall script makes sure ffmped-static binary has proper permissions to function so it runs this `"postinstall": "chmod +x node_modules/ffmpeg-static/ffmpeg",`. If you're running on windows, that might be causing this issue since it expects the command to be a bach shell?

**Comment by Thavarshan** [comment]
you can find it on `package.json`, under `scripts`

**Comment by sebbean** [comment]
I'm running on mac os sonoma

**Comment by sebbean** [comment]
seems to be an API call failing:
<img width="962" alt="image" src="https://github.com/user-attachments/assets/c54ea30b-b496-4551-a63f-892c9e267fd3">

**Comment by Thavarshan** [comment]
In that case, I'll keep an eye on this. See if something else is causing this. Thanks for reporting tho!

**Comment by sebbean** [comment]
of course! looks pretty cool!

i'm usually a vue guy (for web) and I just noticed this app is vue based!

pretty coool!

-sb

**Comment by Thavarshan** [comment]
Closing as this may be a local machine issue
