### ISSUE TITLE
Image conversion

### ISSUE THREAD

**Issue by Thavarshan** [stellar-comet/comet#30]
### Description

This PR requests the addition of an image conversion feature to the Comet media converter. The application currently supports video and audio conversion, but users could greatly benefit from the ability to convert images into various formats as well. The addition of image conversion will further establish Comet as a versatile media conversion tool.

### Feature Details

The requested feature should allow users to convert image files between different popular formats such as JPEG, PNG, BMP, and others. This feature should be integrated seamlessly with the existing bulk file conversion system, allowing users to convert multiple image files at once.

Here are the main requirements for the feature:

- **Supported Formats:** The image conversion feature should support the most common image formats, including but not limited to JPEG, PNG, BMP, GIF, and TIFF.
- **Bulk Image Conversion:** Users should be able to convert multiple images simultaneously, just like they currently can with video and audio files.
- **Output Settings:** There should be options for configuring image quality and format, similar to how video and audio output settings are currently handled.
- **Real-Time Feedback:** The conversion progress for images should be displayed in the same way as it is for video and audio, including real-time updates and error handling.
- **Performance Considerations:** The image conversion should be optimized for speed and resource efficiency, powered by FFmpeg.

#### Additional Information

The image conversion feature will elevate Comet to a more complete media conversion tool, handling all major media types (video, audio, and images). This enhancement would be particularly valuable for users who need to work with multiple types of media files and wish to handle them all within a single, user-friendly application.

**Comment by asdefasdf** [comment]
Let's add this feature to your app.

**Comment by asdefasdf** [comment]
We want such a feature.

**Comment by asdefasdf** [comment]
Let's wait for other updates.
