### ISSUE TITLE
Suggestions for improving the Comet program.

### ISSUE THREAD

**Issue by asdefasdf** [stellar-comet/comet#35]
Suggestions for improving the Comet program.
-When switching from a dark to a light theme, the animation twitches. The same is true on the other side.
It is necessary to ensure smooth running.
-Expand the range of formats available for converting images.
-The Windows installer works fine: installation is silent, but it would be nice to be able to select installation paths.

**Comment by Thavarshan** [comment]
Hi, thank you for your suggestions for improving Comet!

- **Theme switching animation:** We’re aware of the slight twitch when switching between themes. This is related to how CSS transitions are handled, but we’ll continue looking into ways to improve the smoothness where possible.

- **Expanding image formats:** Expanding the range of supported image formats is definitely something we’ve considered. However, supporting more formats would require relying on additional third-party libraries or executables, which might increase the complexity of the project. We’ll explore this option further to see if we can strike a balance.

- **Windows installer paths:** I appreciate the suggestion! The ability to choose installation paths is a great idea, and I’ll make sure this is included in future development discussions. Stay tuned for updates!

Additionally, if you’d like to contribute to these improvements directly, we’d love to see a pull request! Contributions from the community really help the project grow, and we’re happy to collaborate on features like these. Please feel free to submit PRs if you have ideas for implementing these changes.

Thanks again for your feedback, and let’s keep improving Comet together!
