### ISSUE TITLE
We propose to add the ability to convert data for different devices to older models.

### ISSUE THREAD

**Issue by asdefasdf** [stellar-comet/comet#37]
We propose to add the ability to convert data for different devices to older models.

**Comment by Thavarshan** [comment]
Thanks for the suggestion!

Adding support for converting media to formats compatible with older devices is a great idea! We understand the importance of ensuring compatibility with legacy devices, and this could certainly enhance the versatility of Comet. However, older models often require specific formats and codecs that can be tricky to support or maintain.

If you have more details about the formats and devices you're referring to, we’d love to hear them. And of course, if you have experience working with older device formats, we'd encourage you to submit a pull request to help us add this feature to Comet. We're always excited to see community contributions and would welcome your help in making this a reality.

Thanks again for your input!
