### ISSUE TITLE
Add the ability to crop videos or resize images. Also provide the ability to select the cropping angle for images.

### ISSUE THREAD

**Issue by asdefasdf** [stellar-comet/comet#38]
Add the ability to crop videos or resize images. Also provide the ability to select the cropping angle for images.

**Comment by Thavarshan** [comment]
Thanks for the suggestion!

While cropping videos, resizing images, and selecting specific cropping angles are useful features, Comet is focused on providing a simple, efficient media compression and conversion experience. The aim is to keep the app lightweight and easy to use without venturing into advanced media manipulation features like cropping or editing.

However, if you’re looking for more advanced media editing tools, there are other great applications available that specialize in these functions. If you're interested in contributing towards keeping Comet simple yet powerful for compression and conversion, feel free to submit a PR or suggest further ideas that align with our core vision.

Thanks for your feedback!
