### ISSUE TITLE
Add an easy way to extract audio from video.

### ISSUE THREAD

**Issue by asdefasdf** [stellar-comet/comet#40]
Add an easy way to extract audio from video.

**Comment by Thavarshan** [comment]
Thanks for your suggestion!

While extracting audio from video files is a useful feature, Comet is focused on simple, streamlined media conversion. Adding features like audio extraction would move Comet toward video editing, which isn’t the main goal of the app. Our aim is to keep Comet lightweight and easy to use for basic media conversions.

There are several great tools available for more advanced tasks like audio extraction. For now, we’ll be keeping Comet focused on its core functionality.

Thank you again for your input!
